In [6]:
import pandas as pd

df = pd.read_csv(r"output.csv")

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4128 entries, 0 to 4127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           4128 non-null   float64
 1   latitude            4128 non-null   float64
 2   housing_median_age  4128 non-null   int64
 3   total_rooms         4128 non-null   int64
 4   total_bedrooms      4079 non-null   float64
 5   population          4128 non-null   int64
 6   households          4128 non-null   int64
 7   median_income       4128 non-null   float64
 8   ocean_proximity     4128 non-null   object
 9   median_house_value  4128 non-null   float64
 10  predicted_val       4128 non-null   int64
 11  per                 866 non-null    float64
dtypes: float64(6), int64(5), object(1)
memory usage: 387.1+ KB
None

In [ ]:
a = df['median_house_value'].describe()

count      4128.000000
mean     207549.065220
std      102812.908942
min       49099.000000
25%      128516.500000
50%      189070.500000
75%      266774.500000
max      500001.000000
Name: median_house_value, dtype: float64

In [9]:
p= df['predicted_val'].describe()

p

count      4128.000000
mean     206257.795058
std      114176.653346
min       14999.000000
25%      118900.000000
50%      181300.000000
75%      268850.000000
max      500001.000000
Name: predicted_val, dtype: float64

In [11]:
p= df['per'].describe()
p

count    866.000000
mean      -1.541822
std       22.687887
min      -82.409404
25%      -14.164727
50%       -3.853943
75%        6.110288
max      135.794302
Name: per, dtype: float64

In [18]:
df.query("per == 135.794302")

Empty DataFrame
Columns: [longitude, latitude, housing_median_age, total_rooms, total_bedrooms, population, households, median_income, ocean_proximity, median_house_value, predicted_val, per]
Index: []

In [19]:
df.nlargest(1, "per")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,median_house_value,predicted_val,per
219,-117.02,33.6,7,1972,352.0,964,317,3.244,INLAND,143006.0,337200,135.794302